name: hadith_books
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+15

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  animated_background: ^2.0.0
  animated_text_kit: ^4.2.2
  animations: ^2.0.11
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  device_preview: ^1.2.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_launcher_icons: ^0.14.1
  flutter_localizations:
    sdk: flutter
  flutter_share: ^2.0.0
  flutter_staggered_animations: ^1.1.1
  foundation: ^0.0.5
  get_it: ^8.0.0
  get_storage: ^2.1.1
  git: ^2.3.0
  go_router: ^14.3.0
  google_fonts: ^6.2.1
  intl: ^0.19.0
  like_button: ^2.0.5
  lottie: ^3.1.2
  modal_progress_hud_nsn: ^0.5.1
  path: ^1.9.0
  rename: ^3.0.2
  scrollable_positioned_list: ^0.3.8
  sentry_flutter: ^8.9.0
  skeletonizer: ^1.4.2
  sqflite: ^2.3.3
  url_launcher: ^6.3.0
  workmanager: ^0.5.2

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/database/
    - assets/images/
    - assets/animations/

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/app_logo.png"

flutter_intl:
  enabled: true
  arb_dir: lib/config/local/
  template_arb_file: intl_en.arb
  class_name: AppStrings
  output_dir: lib/config/local/
