name: hadith_books
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+23

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  animated_background: ^2.0.0
  animated_text_kit: ^4.2.2
  animations: ^2.0.11
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  device_preview: ^1.2.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_launcher_icons: ^0.14.1
  flutter_localizations:
    sdk: flutter
  flutter_staggered_animations: ^1.1.1
  foundation: ^0.0.5
  get_it: ^8.0.0
  get_storage: ^2.1.1
  git: ^2.3.0
  go_router: ^14.3.0
  google_fonts: ^6.2.1
  intl: ^0.19.0
  like_button: ^2.0.5
  lottie: ^3.1.2
  modal_progress_hud_nsn: ^0.5.1
  page_flip: ^0.2.3
  path: ^1.9.0
  rename: ^3.0.2
  scrollable_positioned_list: ^0.3.8
  sentry_flutter: ^8.9.0
  share_plus: ^10.0.3
  skeletonizer: ^1.4.2
  sqflite: ^2.3.3
  toastification: ^2.3.0
  tutorial_coach_mark: ^1.2.12
  url_launcher: ^6.3.0
  workmanager: ^0.5.2

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/database/
    - assets/database/books/
    - assets/database/search_tria/ar/
    - assets/database/search_tria/en/
    - assets/images/
    - assets/images/books/
    - assets/animations/
    - assets/fonts/amiri/
    - assets/fonts/montserrat/

  fonts:
    - family: Amiri
      fonts:
        - asset: assets/fonts/amiri/Amiri-Regular.ttf
          weight: 400
        - asset: assets/fonts/amiri/Amiri-Bold.ttf
          weight: 700
    - family: Montserrat
      fonts:
        - asset: assets/fonts/montserrat/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/montserrat/Montserrat-Bold.ttf
          weight: 700
    - family: uthmanic
      fonts:
        - asset: assets/fonts/UthmanTN1_Ver10.otf
    - family: uthmanic2
      fonts:
        - asset: assets/fonts/UthmanicHafs_V20.ttf
    - family: kufi
      fonts:
        - asset: assets/fonts/Kufam-Italic-VariableFont_wght.ttf
          style: italic
        - asset: assets/fonts/Kufam-VariableFont_wght.ttf
          weight: 500
        - asset: assets/fonts/Kufam-Regular.ttf
          weight: 100
    - family: naskh
      fonts:
        - asset: assets/fonts/NotoNaskhArabic-VariableFont_wght.ttf
    - family: kfgqpc
      fonts:
        - asset: assets/fonts/KFGQPC-Uthmanic-Script-HAFS-Regular.otf
    - family: arquran
      fonts:
        - asset: assets/fonts/ar-Quran1.ttf
    - family: maddina
      fonts:
        - asset: assets/fonts/MADDINA.ttf
    - family: noorehira
      fonts:
        - asset: assets/fonts/noorehira.ttf
    - family: scheherazade
      fonts:
        - asset: assets/fonts/ScheherazadeRegOT.ttf


flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/app_logo.png"

flutter_intl:
  enabled: true
  arb_dir: lib/config/local/
  template_arb_file: intl_en.arb
  class_name: AppStrings
  output_dir: lib/config/local/
